title: "Marco Di Francesco Portfolio"
description: "📊 Help extracting Meaning out of Data | 🇪🇺 EIT Data Science Msc | 🙋‍♂️ 2024 EIT Student Ambassador"
url: "https://marcodifrancesco.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
email: "marcodifran@gmail.com"
logo: "/assets/icon/logo.png"
lang: "en"
github_username: MarcoDiFrancesco
repository: MarcoDiFrancesco/marcodifrancesco.github.io # Github repository
google_analytics: UA-115310552-1

theme: minima
minima: # Minima date format refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%Y %b" # "%b %-d, %Y"
  social_links: # Generate social links in footer
    linkedin: MarcoDiFran
    # github: MarcoDiFrancesco # I don't want people to go directly to GitHub page. Better if they go to LinkedIn.

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

defaults: # Default settings for posts
  - scope:
      type: "posts"
    values:
      layout: "post"
      author: "Marco Di Francesco"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "file/*.pdf"
    values:
      sitemap: false
  - scope:
      path: "assets/js"
    values:
      sitemap: false
