title: "Marco Di Francesco Portfolio"
description: "Junior Data scientist @ Research center FBK | CS student @ University of Trento"
url: "https://marcodifrancesco.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
email: "info{at}marcodifrancesco.com"
logo: "/assets/icon/logo.png"
lang: "en"
show_excerpts: false # set to true to show excerpts on the homepage
github_username: MarcoDiFrancesco
repository: MarcoDiFrancesco/marcodifrancesco.github.io # Github repository

theme: minima
minima: # Minima date format refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
  date_format: "%b %Y" # "%b %-d, %Y"
  social_links: # Generate social links in footer
    github: MarcoDiFrancesco
    linkedin: MarcoDiFran

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap

defaults: # Default settings for posts
  - scope:
      type: "posts"
    values:
      layout: "post"
      author: "Marco Di Francesco"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "file/*.pdf"
    values:
      sitemap: false
  - scope:
      path: "assets/js"
    values:
      sitemap: false
